sudo: required
services:
    - docker

before_install:
    - docker build -t bentully2077/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bentully2077/react-test npm run test

after_success:
    - docker build -t bentully2077/complex-client ./client
    - docker build -t bentully2077/complex-nginx ./nginx
    - docker build -t bentully2077/complex-server ./server
    - docker build -t bentully2077/complex-worker ./worker
    # log in docker CLI 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take images and push to docker hub
    - docker push bentully2077/complex-client
    - docker push bentully2077/complex-nginx 
    - docker push bentully2077/complex-server 
    - docker push bentully2077/complex-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-853813081120"
    bucket_path: "docker-multi"
    on:
        branch: master                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    
language: generic

