version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        environment:
            # variableName = value (set a variable in the container at *run time)
            # variableName ( value is taken from your computer, useful for api secret key value)
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    #proxy
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
        depends_on: 
            - api
            - client

    api:
        build:
            dockerfile: Dockerfile.dev 
            context: ./server
        volumes:
            #don't override
            - /app/node_modules
            #redirect /app in container to ./server
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379 
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on: 
            - postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379

